workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/build/App.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
