// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydnhzlawgpnsmunwwzqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkbmh6bGF3Z3Buc211bnd3enF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTUyMzQsImV4cCI6MjA2NjY3MTIzNH0.HMS1f2Ogk9D_w26UIeCnWAOlYr9jSbVn3A7jJfiWcBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);